### ISSUE TITLE
projected content even when not asked for

### ISSUE THREAD

**Issue by accowa** [NOC-OI/msm-os#5]
After many failed attempts to get a version of transfer_to_os.sh to work, I've resorted to just trying the serial version. This appears to be trying to work and some output is appearing in the OS. The first command run is:

`msm_os send --file "./eORCA12_1d_grid_T_197601-197601.nc" --bucket "npd12-j001" --append-dim "time_counter" --credentials "./mycreds" -cs '{"time_counter": 1, "x": 720, "y": 360}'`

but:

The log looks like this (it is still running, it is very slow even for these 2D files :( ):

```
Sending ./eORCA12_1d_grid_T_197601-197601.nc to the object store.
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:35 |
          .-~~~-.
  .- ~ ~-(       )_ _
 /                    ~ -.
|          msm-os         ',
 ¬                         .'
   ~- ._ ,. ,.,.,., ,.. -~
           '       '
       version: 0.1.0


☁  msm_os ☁  |       INFO | 2024-06-28 14:38:35 | Reading object store credentials from /home/users/acc/NEMO_cylc/bin/mycreds
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:37 | Sending ./eORCA12_1d_grid_T_197601-197601.nc
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:39 | Skipping npd12-j001/T1d/bounds_nav_lon.zarr because time_counter is not in the dimensions of bounds_nav_lon
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:39 | Skipping npd12-j001/T1d/bounds_nav_lat.zarr because time_counter is not in the dimensions of bounds_nav_lat
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:40 | Appending to npd12-j001/T1d/time_centered_bounds.zarr along the time_counter dimension
☁  msm_os ☁  |    WARNING | 2024-06-28 14:38:42 | Found 31 duplicates in the append dimension 'time_counter'.
☁  msm_os ☁  |    WARNING | 2024-06-28 14:38:42 | Range: 1976-01-01T12:00:00.000000000--1976-01-31T12:00:00.000000000.
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:42 | Skipping npd12-j001/T1d/time_centered_bounds.zarr due to duplicate values in the append dimension
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:43 | Appending to npd12-j001/T1d/time_counter_bounds.zarr along the time_counter dimension
☁  msm_os ☁  |    WARNING | 2024-06-28 14:38:44 | Found 31 duplicates in the append dimension 'time_counter'.
☁  msm_os ☁  |    WARNING | 2024-06-28 14:38:44 | Range: 1976-01-01T12:00:00.000000000--1976-01-31T12:00:00.000000000.
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:44 | Skipping npd12-j001/T1d/time_counter_bounds.zarr due to duplicate values in the append dimension
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:45 | Appending to npd12-j001/T1d/tos_con.zarr along the time_counter dimension
☁  msm_os ☁  |    WARNING | 2024-06-28 14:38:46 | Found 31 duplicates in the append dimension 'time_counter'.
☁  msm_os ☁  |    WARNING | 2024-06-28 14:38:46 | Range: 1976-01-01T12:00:00.000000000--1976-01-31T12:00:00.000000000.
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:46 | Skipping npd12-j001/T1d/tos_con.zarr due to duplicate values in the append dimension
☁  msm_os ☁  |       INFO | 2024-06-28 14:38:46 | Creating npd12-j001/T1d/tossq_con.zarr
☁  msm_os ☁  |       INFO | 2024-06-28 14:39:43 | Setting units to: degC2
☁  msm_os ☁  |       INFO | 2024-06-28 14:39:43 | Setting standard_name to correct value: square_of_sea_surface_temperature
☁  msm_os ☁  |       INFO | 2024-06-28 15:08:03 | Creating npd12-j001/T1d/sossq_abs.zarr
☁  msm_os ☁  |       INFO | 2024-06-28 15:08:47 | Setting units to: 1e-6
☁  msm_os ☁  |       INFO | 2024-06-28 15:08:47 | Warning: Standard Name is not valid. Set long name instead to square_of_sea_surface_Salinity
```

Presumeably, the duplicates mentioned are from earlier attempts that ran out of time? There appears to be data in the bucket, for example:

```
s3cmd ls  s3://npd12-j001/T1d/tos_con.zarr/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/nav_lat/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/nav_lon/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/projected_tos_con/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/projected_x/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/projected_y/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_centered/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_counter/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/tos_con/
2024-06-28 12:40          186  s3://npd12-j001/T1d/tos_con.zarr/.zattrs
2024-06-28 12:40           24  s3://npd12-j001/T1d/tos_con.zarr/.zgroup
2024-06-28 12:41         7131  s3://npd12-j001/T1d/tos_con.zarr/.zmetadata
```
but there are some warnings reported:

```
home/users/acc/.conda/envs/env_cylc/lib/python3.10/site-packages/iris/analysis/cartography.py:687: IrisDefaultingWarning: Coordinate system of latitude and longitude coordinates is not specified. Assuming WGS84 Geodetic.
  warnings.warn(
/home/users/acc/.conda/envs/env_cylc/lib/python3.10/site-packages/iris/analysis/cartography.py:687: IrisDefaultingWarning: Coordinate system of latitude and longitude coordinates is not specified. Assuming WGS84 Geodetic.
  warnings.warn(
/home/users/acc/.conda/envs/env_cylc/lib/python3.10/site-packages/iris/analysis/cartography.py:687: IrisDefaultingWarning: Coordinate system of latitude and longitude coordinates is not specified. Assuming WGS84 Geodetic.
```
which shouldn't be relevant since reprojection has not been asked for. None of my attempts have used the `--reproject` flag so why the warnings and, more importantly, **why does the bucket have entries for the unrequested projected fields?**

**Comment by accowa** [comment]
Tried to fix this but the obvious solution changes the file layout. It looks as if this change  ought to use the `reproject` boolean appropriately:

```diff
--- a/src/msm_os/object_store_handler.py
+++ b/src/msm_os/object_store_handler.py
@@ -390,7 +390,9 @@ def _send_variable(

     except FileNotFoundError:
         logging.info("Creating %s", dest)
-        ds_filepath = _reproject_ds(ds_filepath, var)
+        if reproject:
+            # Reproject the dataset to the expected projection
+            ds_filepath = _reproject_ds(ds_filepath, var)

         ds_filepath = _calculate_metadata(
             xr.Dataset(), ds_filepath, var, append_dim, reproject
```
and, on the surface, it appears to do the job:

```
ls s3://npd12-j001/T1d/
                          DIR  s3://npd12-j001/T1d/bounds_nav_lat.zarr/
                          DIR  s3://npd12-j001/T1d/bounds_nav_lon.zarr/
                          DIR  s3://npd12-j001/T1d/sos_abs.zarr/
                          DIR  s3://npd12-j001/T1d/sossq_abs.zarr/
                          DIR  s3://npd12-j001/T1d/time_centered_bounds.zarr/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/
                          DIR  s3://npd12-j001/T1d/tossq_con.zarr/
```

but data appears to be duplicated in each zarr, e.g.:`time_counter_bounds.zarr`:

```
s3cmd ls s3://npd12-j001/T1d/time_counter_bounds.zarr/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/bounds_nav_lat/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/bounds_nav_lon/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/mlotst/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/nav_lat/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/nav_lon/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/pbo/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/sos_abs/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/sossq_abs/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/time_centered/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/time_centered_bounds/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/time_counter/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/time_counter_bounds/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/tos_con/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/tossq_con/
                          DIR  s3://npd12-j001/T1d/time_counter_bounds.zarr/zos/
2024-07-02 13:12          743  s3://npd12-j001/T1d/time_counter_bounds.zarr/.zattrs
2024-07-02 13:11           24  s3://npd12-j001/T1d/time_counter_bounds.zarr/.zgroup
2024-07-02 13:17        16317  s3://npd12-j001/T1d/time_counter_bounds.zarr/.zmetadata
```
and, again in each zarr, e.g.:

```
s3cmd ls  s3://npd12-j001/T1d/tos_con.zarr/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/bounds_nav_lat/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/bounds_nav_lon/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/mlotst/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/nav_lat/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/nav_lon/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/pbo/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/sos_abs/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/sossq_abs/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_centered/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_centered_bounds/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_counter/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_counter_bounds/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/tos_con/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/tossq_con/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/zos/
2024-07-02 13:18          749  s3://npd12-j001/T1d/tos_con.zarr/.zattrs
2024-07-02 13:17           24  s3://npd12-j001/T1d/tos_con.zarr/.zgroup
2024-07-02 13:22        16323  s3://npd12-j001/T1d/tos_con.zarr/.zmetadata
```
at least the projected variants have disappeared :|

**Comment by accowa** [comment]
I was hoping for something more like this:
```
s3cmd ls s3://tobferchunk6/T1d/
                          DIR  s3://tobferchunk6/T1d/bounds_nav_lat.zarr/
                          DIR  s3://tobferchunk6/T1d/bounds_nav_lon.zarr/
                          DIR  s3://tobferchunk6/T1d/sossq_abs.zarr/
                          DIR  s3://tobferchunk6/T1d/time_centered_bounds.zarr/
                          DIR  s3://tobferchunk6/T1d/time_counter_bounds.zarr/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/
                          DIR  s3://tobferchunk6/T1d/tossq_con.zarr/
s3cmd ls s3://tobferchunk6/T1d/tos_con.zarr/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/nav_lat/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/nav_lon/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/projected_tos_con/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/projected_x/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/projected_y/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/time_centered/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/time_counter/
                          DIR  s3://tobferchunk6/T1d/tos_con.zarr/tos_con/
2024-06-17 13:48          187  s3://tobferchunk6/T1d/tos_con.zarr/.zattrs
2024-06-17 13:48           24  s3://tobferchunk6/T1d/tos_con.zarr/.zgroup
2024-06-17 13:48         7132  s3://tobferchunk6/T1d/tos_con.zarr/.zmetadata
```
but without the `projected_` variants

**Comment by accowa** [comment]
An aside, but possibly related, the zarr files now produced are no longer conformant with netCDF's expectations. They have been in the recent past, for example:
```
/home/users/acc/newTOOLS/nczarr/newjas/bin/ncdump -h https://noc-msm-o.s3-ext.jc.rl.ac.uk/trial-msmos2/T1d#mode=nczarr,s3
netcdf T1d {
dimensions:
	time_counter = 366 ;
	y = 1206 ;
	x = 1440 ;
	axis_nbounds = 2 ;

group: mlotst.zarr {
  variables:
  	float mlotst(time_counter, y, x) ;
  		mlotst:cell_methods = "time: mean (interval: 1800 s)" ;
  		mlotst:coordinates = "time_centered nav_lat nav_lon" ;
  		mlotst:interval_operation = "1800 s" ;
  		mlotst:interval_write = "1 d" ;
  		mlotst:long_name = "Ocean Mixed Layer Thickness Defined by Sigma T" ;
  		mlotst:missing_value = 1.00000002004088e+20 ;
  		mlotst:online_operation = "average" ;
  		mlotst:standard_name = "ocean_mixed_layer_thickness_defined_by_sigma_theta" ;
  		mlotst:units = "m" ;
  	float nav_lat(y, x) ;
  		nav_lat:long_name = "Latitude" ;
  		nav_lat:standard_name = "latitude" ;
  		nav_lat:units = "degrees_north" ;
  	float nav_lon(y, x) ;
  		nav_lon:long_name = "Longitude" ;
  		nav_lon:standard_name = "longitude" ;
  		nav_lon:units = "degrees_east" ;
  	double time_centered(time_counter) ;
  		time_centered:bounds = "time_centered_bounds" ;
  		time_centered:calendar = "gregorian" ;
  		time_centered:long_name = "Time axis" ;
  		time_centered:standard_name = "time" ;
  		time_centered:time_origin = "1900-01-01 00:00:00" ;
  		time_centered:units = "seconds since 1900-01-01" ;
  	double time_counter(time_counter) ;
  		time_counter:axis = "T" ;
  		time_counter:bounds = "time_counter_bounds" ;
  		time_counter:calendar = "gregorian" ;
  		time_counter:long_name = "Time axis" ;
  		time_counter:standard_name = "time" ;
  		time_counter:time_origin = "1900-01-01 00:00:00" ;
  		time_counter:units = "seconds since 1900-01-01" ;
  } // group mlotst.zarr
.
.
```
but newer files throw up an error:
```
/home/users/acc/newTOOLS/nczarr/newjas/bin/ncdump -h https://noc-msm-o.s3-ext.jc.rl.ac.uk/tobfer10/T1d#mode=nczarr,s3
/home/users/acc/newTOOLS/nczarr/newjas/bin/ncdump: https://noc-msm-o.s3-ext.jc.rl.ac.uk/tobfer10/T1d#mode=nczarr,s3: NetCDF: Invalid dimension size

s3cmd ls s3://tobfer10/
                          DIR  s3://tobfer10/T1d/
                          DIR  s3://tobfer10/T1m/
                          DIR  s3://tobfer10/T1y/
                          DIR  s3://tobfer10/T5d/
                          DIR  s3://tobfer10/U1d/
                          DIR  s3://tobfer10/U1m/
                          DIR  s3://tobfer10/U1y/
                          DIR  s3://tobfer10/V1d/
                          DIR  s3://tobfer10/V1m/
                          DIR  s3://tobfer10/V1y/
                          DIR  s3://tobfer10/W1m/
                          DIR  s3://tobfer10/W1y/
                          DIR  s3://tobfer10/icemod1m/
                          DIR  s3://tobfer10/icemod1y/
                          DIR  s3://tobfer10/scalar1d/
                          DIR  s3://tobfer10/scalar1m/
                          DIR  s3://tobfer10/scalar1y/
```

**Comment by soutobias** [comment]
@accowa , I created a branch and updated the reproject code. About the duplicated variables, I will check it.

**Comment by soutobias** [comment]
I tried to reproduce your error, but I am not getting duplicated data here: 

```
(nemocycl) ➜  NEMO_cylc git:(dev) s3cmd ls s3://npd12-j001/T1d/tos_con.zarr/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/nav_lat/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/nav_lon/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_centered/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/time_counter/
                          DIR  s3://npd12-j001/T1d/tos_con.zarr/tos_con/
2024-07-08 11:49          157  s3://npd12-j001/T1d/tos_con.zarr/.zattrs
2024-07-08 11:49           24  s3://npd12-j001/T1d/tos_con.zarr/.zgroup
2024-07-08 11:50         5013  s3://npd12-j001/T1d/tos_con.zarr/.zmetadata
```

Did you correct the data on your bucket?

**Comment by accowa** [comment]
> Did you correct the data on your bucket?

Yes, I've hacked a version of `object_store_handler.py` that kind of works but I'm not sure it will append properly and the intervention is inside `_reproject_ds`. The code needs rewriting so that` _reproject_ds` isn't needed at all if reprojection is not requested.

```diff
--- a/src/msm_os/object_store_handler.py
+++ b/src/msm_os/object_store_handler.py
@@ -328,7 +328,7 @@ def _send_variable(
             check_duplicates(ds_filepath, ds_obj_store, append_dim)
             if reproject:
                 # Reproject the dataset to the expected projection
-                ds_filepath = _reproject_ds(ds_filepath, var)
+                ds_filepath = _reproject_ds(ds_filepath, var, reproject)

             # Calculate expected size, variables, chunks and checksum
             ds_filepath = _calculate_metadata(
@@ -390,7 +390,8 @@ def _send_variable(

     except FileNotFoundError:
         logging.info("Creating %s", dest)
-        ds_filepath = _reproject_ds(ds_filepath, var)
+        # If required, reproject the dataset to the expected projection
+        ds_filepath = _reproject_ds(ds_filepath, var, reproject )

         ds_filepath = _calculate_metadata(
             xr.Dataset(), ds_filepath, var, append_dim, reproject

-def _reproject_ds(ds_filepath: xr.Dataset, var: str) -> xr.Dataset:
+def _reproject_ds(ds_filepath: xr.Dataset, var: str, reproject: bool ) -> xr.Dataset:
     """
-    Reproject the dataset to the expected projection.
+    Possibly reproject the dataset to the expected projection.

     Parameters
     ----------
@@ -437,6 +440,8 @@ def _reproject_ds(ds_filepath: xr.Dataset, var: str) -> xr.Dataset:
         The dataset to be reprojected.
     var : str
         The name of the variable to be reprojected.
+    reproject : bool
+        Switch to decide id reprojection is required

     Returns
     -------
@@ -461,6 +466,11 @@ def _reproject_ds(ds_filepath: xr.Dataset, var: str) -> xr.Dataset:
     if units:
         da_filepath.attrs["units"] = None

+    if not reproject:
+        combined_ds = xr.Dataset({var: da_filepath})
+        return combined_ds
+
     cube = da_filepath.to_iris()
     for coord in cube.aux_coords:
         if coord.standard_name == "latitude":
@@ -566,6 +576,10 @@ def _calculate_metadata(
     # Calculate expected variables and coords for the dataset
     expected_variables = list(set(list(ds_obj_store.keys()) + list(ds_filepath.keys())))
     expected_coords = list(set(list(ds_obj_store.coords) + list(ds_obj_store.coords)))
+    if not expected_variables:
+      expected_variables = ["none"]
+    if not expected_coords:
+      expected_coords = ["none"]
     ds_filepath.attrs["expected_variables"] = expected_variables
     ds_filepath.attrs["expected_coords"] = expected_coords

```

**Comment by accowa** [comment]
Has the latest pull-request been tested? It doesn't work for me. Looks like it is trying to append to a non-existent bucket.:

```
Traceback (most recent call last):
  File "/home/users/acc/.conda/envs/env_cylc/lib/python3.10/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
  File "/home/users/acc/.conda/envs/env_cylc/lib/python3.10/site-packages/aiobotocore/client.py", line 411, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
```
I think you still need some of the code in _reproject_ds to initialise the bucket even when reprojection is not wanted. Hence the:

```
+    if not reproject:
+        combined_ds = xr.Dataset({var: da_filepath})
+        return combined_ds
+
```

part of my hack above. However, we need a better solution.
